### ISSUE TITLE
no DownloadFile funtion

### ISSUE THREAD

**Issue by CrocdileChan** [linxGnu/goseaweedfs#1]
hi,
recently,  I use seaweedfs and find some seaweedfs-client.
I prepare to use your seaweedfs-client ,but it does not  have a function that can download the file from weedfs,  I only find some lookup function to lookup volumeID , url .

Could you please add a DownloadFile function into  your client library?

Thanks!

**Comment by linxGnu** [comment]
I am so sorry for extremely late reply because I had big job change this time.

So, did you solve the problem? If not, please tell me what you want the feature in detail? 

AFAIK, you could directly access/download file via fileID/filename from seaweedfs without the need of client feature. It should be better if you let me know your use case.

Thanks in advance.

**Comment by linxGnu** [comment]
Sound great! 

Thank you very much. I am looking forward to see your PR.

**Comment by linxGnu** [comment]
I will close the issue due to PR #2
